import { useEffect, useState } from 'react'
import { api } from '../api'

function Breadcrumbs({ problem }) {
  return <nav aria-label="Breadcrumb" className="mb-6 flex flex-wrap items-center gap-1 text-sm">
    <a href="/dashboard" className="font-medium text-violet-400 hover:text-violet-300">/dashboard</a><span className="text-violet-500">/</span>
    <a href="/roadmap" className="font-medium text-violet-400 hover:text-violet-300">/DSA Roadmap</a>
    {problem?.topic?.id ? <><span className="text-violet-500">/</span><a href={`/topic/${problem.topic.id}`} className="font-medium text-violet-400 hover:text-violet-300">/{problem.topic.name}</a></> : null}
    <span className="text-violet-500">/</span><span className="font-medium text-violet-300">/{problem?.title || 'Solution'}</span>
  </nav>
}

function StatusButton({ problem, onStatusChange }) {
  const solved = problem.status === 'solved'
  return <button type="button" onClick={() => onStatusChange(problem.id, solved ? 'not_started' : 'solved')} className={`inline-flex h-9 cursor-pointer items-center gap-2 rounded-lg border px-3 text-xs font-semibold transition ${solved ? 'border-emerald-500 bg-emerald-500 text-white' : 'border-slate-300 bg-white text-slate-600 hover:bg-slate-50 dark:border-[#3a3a3a] dark:bg-[#171717] dark:text-slate-300 dark:hover:bg-[#242424]'}`}><span className={`inline-flex h-5 w-5 items-center justify-center rounded-md border text-xs ${solved ? 'border-white bg-white text-emerald-600' : 'border-current text-transparent'}`}>✓</span>{solved ? 'Solved' : 'Mark solved'}</button>
}
function BookmarkButton({ problem, onBookmarkChange }) { const active=Boolean(problem.bookmarked); return <button type="button" onClick={() => onBookmarkChange(problem.id, active)} className="inline-flex h-9 cursor-pointer items-center gap-2 rounded-lg border border-amber-500/40 bg-amber-500/10 px-3 text-xs font-semibold text-amber-700 hover:bg-amber-500/20 dark:text-amber-200"><span className="text-base leading-none">{active?'★':'☆'}</span>{active?'Bookmarked':'Bookmark'}</button> }
function RevisionButton({ problem, onRevisionChange }) { const active=Boolean(problem.revision); return <button type="button" onClick={() => onRevisionChange(problem.id,!active)} className={`inline-flex h-9 cursor-pointer items-center gap-2 rounded-lg border px-3 text-xs font-semibold transition ${active?'border-sky-500 bg-sky-500 text-white':'border-slate-300 bg-white text-slate-600 hover:bg-slate-50 dark:border-[#3a3a3a] dark:bg-[#171717] dark:text-slate-300 dark:hover:bg-[#242424]'}`}>↻ {active?'Revision':'Add revision'}</button> }

function Section({ title, children }) {
  const [open,setOpen]=useState(false)
  return <section className="overflow-hidden rounded-xl border border-slate-300 bg-white dark:border-[#333333] dark:bg-[#181818]"><button type="button" onClick={()=>setOpen(v=>!v)} aria-expanded={open} className="flex w-full cursor-pointer items-center justify-between px-5 py-4 text-left text-sm font-semibold text-slate-800 hover:bg-slate-50 dark:text-slate-100 dark:hover:bg-[#222222]"><span>{title}</span><span className="text-lg leading-none text-slate-500 dark:text-slate-400">{open?'⌃':'⌄'}</span></button>{open?<div className="border-t border-slate-200 px-5 py-5 dark:border-[#333333]">{children}</div>:null}</section>
}
function TextBlock({ text }) { return <div className="whitespace-pre-wrap text-sm leading-7 text-slate-700 dark:text-slate-300">{text || 'Not available yet.'}</div> }

function SolutionPage({ problemId, onStatusChange, onRevisionChange, onBookmarkChange }) {
  const [data,setData]=useState(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
  useEffect(()=>{let cancelled=false; async function load(){setLoading(true);setError('');try{const result=await api.getSolution(problemId);if(!cancelled)setData(result)}catch(e){if(!cancelled)setError(e.message||'Unable to load the solution.')}finally{if(!cancelled)setLoading(false)}} if(problemId)load(); return()=>{cancelled=true}},[problemId])
  if(loading)return <div className="rounded-xl border border-slate-300 bg-white p-8 text-center text-sm text-slate-500 dark:border-[#333333] dark:bg-[#181818] dark:text-slate-400">Loading solution…</div>
  if(error)return <div className="rounded-xl border border-rose-900/50 bg-rose-950/20 p-6 text-sm text-rose-300">{error}</div>
  if(!data?.problem)return <div className="rounded-xl border border-slate-300 bg-white p-8 text-center dark:border-[#333333] dark:bg-[#181818]">Problem not found.</div>
  const {problem,solution}=data
  async function toggleStatus(){const next=problem.status==='solved'?'not_started':'solved';await onStatusChange(problem.id,next);setData(c=>({...c,problem:{...c.problem,status:next}}))}
  async function toggleBookmark(){const active=Boolean(problem.bookmarked);await onBookmarkChange(problem.id,active);setData(c=>({...c,problem:{...c.problem,bookmarked:!active}}))}
  async function toggleRevision(){const active=Boolean(problem.revision);await onRevisionChange(problem.id,!active);setData(c=>({...c,problem:{...c.problem,revision:!active}}))}
  if(!solution?.available)return <><Breadcrumbs problem={problem}/><h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">{problem.title}</h1><p className="mt-2 text-sm text-slate-500 dark:text-slate-400 capitalize">{problem.difficulty} · {problem.topic?.name||'DSA'}</p><div className="mt-8 min-h-[420px] rounded-xl border border-slate-300 bg-white dark:border-[#333333] dark:bg-[#181818]" /></>
  const videoUrl=solution.video_url||problem.youtube_url
  return <><Breadcrumbs problem={problem}/><div className="mb-6 flex flex-col gap-4 border-b border-slate-200 pb-6 dark:border-[#333333]"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">{problem.title}</h1><div className="mt-2 flex flex-wrap items-center gap-2 text-sm text-slate-500 dark:text-slate-400"><span className="capitalize">{problem.difficulty}</span>{problem.pattern?<><span>·</span><span>{problem.pattern}</span></>:null}</div></div><div className="flex flex-wrap gap-2"><StatusButton problem={problem} onStatusChange={toggleStatus}/><BookmarkButton problem={problem} onBookmarkChange={toggleBookmark}/><RevisionButton problem={problem} onRevisionChange={toggleRevision}/></div></div></div>
    <section className="mb-4"><h2 className="mb-3 text-lg font-semibold">Problem Statement</h2><TextBlock text={solution.problem_statement}/></section>
    <div className="space-y-3"><Section title="Examples"><TextBlock text={solution.examples}/></Section><Section title="Brute force Approach"><TextBlock text={solution.brute_force||problem.brute_force}/></Section><Section title="Better Approach"><TextBlock text={solution.better_approach}/></Section><Section title="Optimal Approach"><TextBlock text={solution.optimal_approach||problem.optimal_approach}/></Section><Section title={`Solution / Code${solution.code_language?` · ${solution.code_language}`:''}`}><div className="overflow-x-auto rounded-lg border border-slate-300 bg-slate-50 dark:border-[#333333] dark:bg-[#101010]"><pre className="min-w-max p-5 text-sm leading-6 text-slate-800 dark:text-slate-200"><code>{solution.code||'Code not available yet.'}</code></pre></div>{solution.code?<button type="button" onClick={()=>navigator.clipboard?.writeText(solution.code)} className="mt-3 cursor-pointer rounded-lg border border-slate-300 bg-white px-3 py-2 text-xs font-semibold text-slate-600 hover:bg-slate-50 dark:border-[#3a3a3a] dark:bg-[#171717] dark:text-slate-300 dark:hover:bg-[#242424]">Copy code</button>:null}</Section><Section title="Video Solution"><div className="text-sm leading-7 text-slate-700 dark:text-slate-300">{videoUrl?<a href={videoUrl} target="_blank" rel="noreferrer" className="font-semibold text-violet-600 hover:text-violet-500 dark:text-violet-300">Watch video solution on YouTube</a>:'Video solution not available yet.'}</div></Section></div>
    <div className="mt-6 flex flex-wrap gap-2 border-t border-slate-200 pt-5 dark:border-[#333333]">{problem.leetcode_url?<a href={problem.leetcode_url} target="_blank" rel="noreferrer" className="inline-flex h-8 items-center justify-center rounded-lg border border-violet-500/40 bg-violet-500/10 px-2.5 text-xs font-semibold text-violet-700 hover:bg-violet-500/20 dark:text-violet-200">LeetCode</a>:null}{problem.gfg_url?<a href={problem.gfg_url} target="_blank" rel="noreferrer" className="inline-flex h-8 items-center justify-center rounded-lg border border-emerald-500/40 bg-emerald-500/10 px-2.5 text-xs font-semibold text-emerald-700 hover:bg-emerald-500/20 dark:text-emerald-200">GFG</a>:null}{problem.article_url?<a href={problem.article_url} target="_blank" rel="noreferrer" className="inline-flex h-8 items-center justify-center rounded-lg border border-amber-500/40 bg-amber-500/10 px-2.5 text-xs font-semibold text-amber-700 hover:bg-amber-500/20 dark:text-amber-200">TUF</a>:null}{problem.youtube_url?<a href={problem.youtube_url} target="_blank" rel="noreferrer" className="inline-flex h-8 items-center justify-center rounded-lg border border-rose-500/40 bg-rose-500/10 px-2.5 text-xs font-semibold text-rose-700 hover:bg-rose-500/20 dark:text-rose-200">YouTube</a>:null}</div>
  </>
}
export default SolutionPage
